[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.119.0",
    "pydantic>=2.12.3",
    "python-dotenv>=1.1.1",
    "uvicorn[standard]>=0.37.0",
]
