apiVersion: v1
kind: ConfigMap
metadata:
  name: nexusplanner-config
  namespace: nexusplanner
data:
  # Application Configuration
  APP_NAME: "NexusPlanner"
  APP_VERSION: "2.0.0"
  
  # AI Provider Selection
  LLM_PROVIDER: "bedrock"  # Options: openai, bedrock, rule-based
  USE_AI_GENERATION: "true"
  
  # AWS Bedrock Configuration
  AWS_REGION: "us-east-1"
  BEDROCK_MODEL_NAME: "claude-3-5-sonnet"
  
  # OpenAI Configuration (if using OpenAI)
  OPENAI_MODEL: "gpt-5"
  
  # Application Settings
  RUN_MIGRATIONS_ON_STARTUP: "true"
  ENABLE_DATABASE_LOGGING: "true"
  AGENT_LOG_RETENTION_DAYS: "90"
  
  # CORS Configuration (adjust for your domain)
  CORS_ORIGINS: '["https://nexusplanner.example.com"]'
  
  # JWT Configuration
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "480"
