apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nexusplanner-backend-pdb
  namespace: nexusplanner
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nexusplanner
      component: backend

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nexusplanner-frontend-pdb
  namespace: nexusplanner
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: nexusplanner
      component: frontend
